version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - cicd_network

networks:
  cicd_network:
    driver: bridge
